application: 'Protein Classification'

training:
  train_on_validation: False
  batch_size: 4
  num_workers: 4
  learning_rate: 0.001
  train_val_split: 0.8
  num_epochs: 50
  tb_log_dir: './log/'
  continue_train_id:
  enable_gpu: False
  save_model: True
  compute_metrics : True
  compute_metrics_every: 5

model:
  feature_extractor: 'resnet34'
  image_size: 512
  pretrained: True

data_pipe:
  path: 'D:\master\Bio\project\human-protein-atlas-image-classification'
  annotations: 'train.csv'
  train_dir: 'train'
  test_dir: 'test'