application: 'Protein Classification'

training:
  train_on_validation: False
  batch_size: 4
  num_workers: 4
  learning_rate: 0.001
  train_val_split: 0.8
  image_size: [128, 128]
  num_epochs: 50
  save_model: True

model:
  type: 'resnet18'
  continue_training: False
  weights_path: 'checkpoints/'

data_pipe:
  path: 'D:\master\Bio\project\human-protein-atlas-image-classification'
  annotations: 'train.csv'
  train_dir: 'train'
  test_dir: 'test'